# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Home(object):
    def setupUi(self, Home):
        Home.setObjectName("Home")
        Home.resize(1015, 690)
        icon = QtGui.QIcon()

        Home.setWindowFlag(QtCore.Qt.FramelessWindowHint)

        Home.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        icon.addPixmap(QtGui.QPixmap(":/hinh/image/cpu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Home.setWindowIcon(icon)
        Home.setStyleSheet("border-raidus:50px\n"
"")
        Home.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(Home)
        self.centralwidget.setObjectName("centralwidget")
        self.nen = QtWidgets.QLabel(self.centralwidget)
        self.nen.setGeometry(QtCore.QRect(20, 40, 941, 611))
        self.nen.setStyleSheet("border-image: url(:/hinh/image/nen_home.png);\n"
"border-radius:15px;\n"
"")
        self.nen.setText("")
        self.nen.setScaledContents(False)
        self.nen.setObjectName("nen")
        self.home = QtWidgets.QPushButton(self.centralwidget)
        self.home.setEnabled(False)
        self.home.setGeometry(QtCore.QRect(40, 100, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.home.setFont(font)
        self.home.setStyleSheet("QPushButton {\n"
"\n"
"\n"
";\n"
"    background-color: rgb(255, 170, 0);\n"
"     color: black;\n"
"   border: 1px solid white; /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hinh/image/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home.setIcon(icon1)
        self.home.setIconSize(QtCore.QSize(30, 30))
        self.home.setAutoDefault(False)
        self.home.setDefault(False)
        self.home.setFlat(False)
        self.home.setObjectName("home")
        self.manager = QtWidgets.QPushButton(self.centralwidget)
        self.manager.setEnabled(True)
        self.manager.setGeometry(QtCore.QRect(40, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.manager.setFont(font)
        self.manager.setStyleSheet("\n"
"\n"
"QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"    color: black;\n"
"    border: 2px solid grey;     /* viền đen */\n"
"\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hinh/image/planning (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manager.setIcon(icon2)
        self.manager.setIconSize(QtCore.QSize(30, 30))
        self.manager.setCheckable(False)
        self.manager.setAutoDefault(False)
        self.manager.setObjectName("manager")
        self.btn_ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_.setGeometry(QtCore.QRect(960, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_.setFont(font)
        self.btn_.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color: black;\n"
"   border: 1px solid black;    /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        self.btn_.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hinh/image/reject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_.setIcon(icon3)
        self.btn_.setIconSize(QtCore.QSize(20, 20))
        self.btn_.setObjectName("btn_")
        self.btn_logout_home = QtWidgets.QPushButton(self.centralwidget)
        self.btn_logout_home.setGeometry(QtCore.QRect(40, 280, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_home.setFont(font)
        self.btn_logout_home.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color: black;\n"
"   border: 2px solid grey;    /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/hinh/image/exit (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout_home.setIcon(icon4)
        self.btn_logout_home.setIconSize(QtCore.QSize(25, 30))
        self.btn_logout_home.setAutoDefault(False)
        self.btn_logout_home.setDefault(False)
        self.btn_logout_home.setFlat(False)
        self.btn_logout_home.setObjectName("btn_logout_home")
        self.contact = QtWidgets.QPushButton(self.centralwidget)
        self.contact.setGeometry(QtCore.QRect(40, 220, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.contact.setFont(font)
        self.contact.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color: black;\n"
"   border: 2px solid grey;    /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hinh/image/contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contact.setIcon(icon5)
        self.contact.setIconSize(QtCore.QSize(30, 30))
        self.contact.setObjectName("contact")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 0, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 101, 31))
        self.label_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 0, 29, 29))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/hinh/image/home.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.nen.raise_()
        self.home.raise_()
        self.manager.raise_()
        self.btn_.raise_()
        self.btn_logout_home.raise_()
        self.contact.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        Home.setCentralWidget(self.centralwidget)

        self.retranslateUi(Home)
        QtCore.QMetaObject.connectSlotsByName(Home)

    def retranslateUi(self, Home):
        _translate = QtCore.QCoreApplication.translate
        Home.setWindowTitle(_translate("Home", "Home"))
        self.home.setText(_translate("Home", "Home"))
        self.manager.setText(_translate("Home", "Manager"))
        self.btn_logout_home.setText(_translate("Home", "Back to login"))
        self.contact.setText(_translate("Home", "Contact"))
        self.label_2.setText(_translate("Home", "Home"))
import Cpu_hinh


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Home = QtWidgets.QMainWindow()
    ui = Ui_Home()
    ui.setupUi(Home)
    Home.show()
    sys.exit(app.exec_())
