# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAIN_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1581, 891)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hinh/image/cpu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 1581, 891))
        self.label_10.setStyleSheet("background-image: url(:/hinh/image/nenleft.jpg);\n"
"")

        self.label_10.setText("")
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.sidebar = QtWidgets.QFrame(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(40, 30, 291, 821))
        self.sidebar.setStyleSheet("\n"
"\n"
"\n"
"border-radius:20px;\n"
"background-color: #1E1E2F;\n"
"background-color: rgba(45, 62, 80, 0.8); ")
        self.sidebar.setObjectName("sidebar")
        self.btn_manager = QtWidgets.QPushButton(self.sidebar)
        self.btn_manager.setEnabled(False)
        self.btn_manager.setGeometry(QtCore.QRect(30, 430, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_manager.setFont(font)
        self.btn_manager.setStyleSheet("QPushButton {\n"
"\n"
"\n"
";\n"
"    background-color: rgb(255, 170, 0);\n"
"     color: black;\n"
"   border: 2px solid black; /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hinh/image/types.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_manager.setIcon(icon1)
        self.btn_manager.setIconSize(QtCore.QSize(44, 44))
        self.btn_manager.setCheckable(False)
        self.btn_manager.setAutoDefault(False)
        self.btn_manager.setObjectName("btn_manager")
        self.btn_type = QtWidgets.QPushButton(self.sidebar)
        self.btn_type.setGeometry(QtCore.QRect(30, 510, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_type.setFont(font)
        self.btn_type.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color: black;\n"
"     border: 2px solid black;    /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hinh/image/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_type.setIcon(icon2)
        self.btn_type.setIconSize(QtCore.QSize(44, 44))
        self.btn_type.setObjectName("btn_type")
        self.btn_logout = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout.setGeometry(QtCore.QRect(30, 590, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout.setFont(font)
        self.btn_logout.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color: black;\n"
"   border: 2px solid black;    /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hinh/image/exit (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout.setIcon(icon3)
        self.btn_logout.setIconSize(QtCore.QSize(44, 44))
        self.btn_logout.setObjectName("btn_logout")
        self.pb_home = QtWidgets.QPushButton(self.sidebar)
        self.pb_home.setGeometry(QtCore.QRect(30, 350, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pb_home.setFont(font)
        self.pb_home.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"    color: black;\n"
"    border: 2px solid black;     /* viền đen */\n"
"\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/hinh/image/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_home.setIcon(icon4)
        self.pb_home.setIconSize(QtCore.QSize(44, 44))
        self.pb_home.setObjectName("pb_home")
        self.logoLabel = QtWidgets.QLabel(self.sidebar)
        self.logoLabel.setGeometry(QtCore.QRect(0, 0, 291, 311))
        self.logoLabel.setStyleSheet("border-bottom-left-radius: 999px;\n"
"border-image: url(:/hinh/image/logo.png);\n"
"")
        self.logoLabel.setText("")
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.btn_logout_2 = QtWidgets.QPushButton(self.sidebar)
        self.btn_logout_2.setGeometry(QtCore.QRect(30, 670, 221, 61))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.btn_logout_2.setFont(font)
        self.btn_logout_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color: black;\n"
"   border: 2px solid black;    /* viền đen */\n"
"    border-radius: 20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hinh/image/reject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_logout_2.setIcon(icon5)
        self.btn_logout_2.setIconSize(QtCore.QSize(44, 44))
        self.btn_logout_2.setObjectName("btn_logout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.sidebar)
        self.groupBox_4.setGeometry(QtCore.QRect(9, 310, 271, 441))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(14)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;\n"
"     \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_4.raise_()
        self.logoLabel.raise_()
        self.btn_manager.raise_()
        self.btn_type.raise_()
        self.btn_logout.raise_()
        self.pb_home.raise_()
        self.btn_logout_2.raise_()
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(360, 40, 1181, 811))
        self.widget.setStyleSheet("\n"
"BORDER-RADIUS:50PX;\n"
"background-color: rgba(45, 62, 80, 0.8); /* 0.8 là độ mờ, bạn có thể thay đổi từ 0 (trong suốt) đến 1 (đậm hoàn toàn) */\n"
"background-color: #1E1E2F;\n"
"\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.pic = QtWidgets.QGroupBox(self.widget)
        self.pic.setGeometry(QtCore.QRect(30, 30, 1121, 351))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.pic.setFont(font)
        self.pic.setAutoFillBackground(False)
        self.pic.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;          /* Khoảng cách giữa tiêu đề và nội dung */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 1px;\n"
"    color: white;              /* Màu tiêu đề */\n"
"    font-weight: bold;\n"
"}\n"
"/* Phần dropdown (popup) */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"    selection-background-color: #3399FF;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Các mục riêng lẻ trong dropdown */\n"
"QComboBox::item {\n"
"    color: black;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* Mục đang được hiển thị (mục mặc định hoặc đã chọn) */\n"
"QComboBox::drop-down {\n"
"    color: black;\n"
"}\n"
"\n"
"/* Khi hover hoặc chọn item */\n"
"QComboBox::item:selected {\n"
"    background-color: #3399FF;\n"
"    color: white;\n"
"}\n"
"")
        self.pic.setFlat(False)
        self.pic.setCheckable(False)
        self.pic.setObjectName("pic")
        self.pb_add = QtWidgets.QPushButton(self.pic)
        self.pb_add.setGeometry(QtCore.QRect(130, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_add.setFont(font)
        self.pb_add.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 0);\n"
"     color: black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/hinh/image/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_add.setIcon(icon6)
        self.pb_add.setObjectName("pb_add")
        self.pb_delete = QtWidgets.QPushButton(self.pic)
        self.pb_delete.setGeometry(QtCore.QRect(580, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_delete.setFont(font)
        self.pb_delete.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 255);\n"
"color: black;\n"
"\n"
"    \n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/hinh/image/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_delete.setIcon(icon7)
        self.pb_delete.setObjectName("pb_delete")
        self.pb_modi = QtWidgets.QPushButton(self.pic)
        self.pb_modi.setGeometry(QtCore.QRect(280, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_modi.setFont(font)
        self.pb_modi.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 204, 170);\n"
"     color: black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/hinh/image/editing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_modi.setIcon(icon8)
        self.pb_modi.setObjectName("pb_modi")
        self.pb_cancel = QtWidgets.QPushButton(self.pic)
        self.pb_cancel.setGeometry(QtCore.QRect(430, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_cancel.setFont(font)
        self.pb_cancel.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/hinh/image/paper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_cancel.setIcon(icon9)
        self.pb_cancel.setObjectName("pb_cancel")
        self.groupBox_3 = QtWidgets.QGroupBox(self.pic)
        self.groupBox_3.setGeometry(QtCore.QRect(820, 40, 161, 191))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;          /* Khoảng cách giữa tiêu đề và nội dung */\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 1px;\n"
"    color: white;              /* Màu tiêu đề */\n"
"    font-weight: bold;\n"
"}\n"
"")
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(480, 50, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(480, 100, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.rd_full = QtWidgets.QRadioButton(self.groupBox_3)
        self.rd_full.setGeometry(QtCore.QRect(40, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rd_full.setFont(font)
        self.rd_full.setStyleSheet("color: rgb(255, 255, 255);")
        self.rd_full.setObjectName("rd_full")
        self.rd_no = QtWidgets.QRadioButton(self.groupBox_3)
        self.rd_no.setGeometry(QtCore.QRect(40, 110, 75, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rd_no.setFont(font)
        self.rd_no.setStyleSheet("color: rgb(255, 255, 255);")
        self.rd_no.setObjectName("rd_no")
        self.label = QtWidgets.QLabel(self.pic)
        self.label.setGeometry(QtCore.QRect(130, 50, 31, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.le_id = QtWidgets.QLineEdit(self.pic)
        self.le_id.setGeometry(QtCore.QRect(164, 40, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.le_id.setFont(font)
        self.le_id.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.le_id.setText("")
        self.le_id.setObjectName("le_id")
        self.le_name = QtWidgets.QLineEdit(self.pic)
        self.le_name.setGeometry(QtCore.QRect(164, 110, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.le_name.setFont(font)
        self.le_name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.le_name.setText("")
        self.le_name.setObjectName("le_name")
        self.le_price = QtWidgets.QLineEdit(self.pic)
        self.le_price.setGeometry(QtCore.QRect(164, 190, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.le_price.setFont(font)
        self.le_price.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.le_price.setText("")
        self.le_price.setObjectName("le_price")
        self.label_3 = QtWidgets.QLabel(self.pic)
        self.label_3.setGeometry(QtCore.QRect(100, 130, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.pic)
        self.label_2.setGeometry(QtCore.QRect(110, 208, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.cb_compa = QtWidgets.QComboBox(self.pic)
        self.cb_compa.setGeometry(QtCore.QRect(530, 40, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.cb_compa.setFont(font)
        self.cb_compa.setStyleSheet("QComboBox {\n"
"    background-color: white;\n"
"    color: black;\n"
"    border: 1px solid #00CFFF;\n"
"    padding: 5px;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"/* Phần dropdown (popup) */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: white;\n"
"    color: black;\n"
"    selection-background-color: #3399FF;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* ĐẢM BẢO: Các item riêng lẻ có màu chữ đúng khi chưa được chọn */\n"
"QComboBox::item {\n"
"    color: black;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* Khi hover/chọn item */\n"
"QComboBox::item:selected {\n"
"    background-color: #3399FF;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.cb_compa.setObjectName("cb_compa")
        self.cb_compa.addItem("")
        self.cb_compa.addItem("")
        self.cb_compa.addItem("")
        self.label_5 = QtWidgets.QLabel(self.pic)
        self.label_5.setGeometry(QtCore.QRect(430, 50, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.pic)
        self.label_6.setGeometry(QtCore.QRect(430, 130, 91, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.cb_process = QtWidgets.QComboBox(self.pic)
        self.cb_process.setGeometry(QtCore.QRect(530, 110, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.cb_process.setFont(font)
        self.cb_process.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.cb_process.setObjectName("cb_process")
        self.cb_process.addItem("")
        self.pb_findcompa = QtWidgets.QPushButton(self.pic)
        self.pb_findcompa.setGeometry(QtCore.QRect(720, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_findcompa.setFont(font)
        self.pb_findcompa.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 255, 0);\n"
"     color: black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/hinh/image/research.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_findcompa.setIcon(icon10)
        self.pb_findcompa.setObjectName("pb_findcompa")
        self.lineEdit = QtWidgets.QLineEdit(self.pic)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setGeometry(QtCore.QRect(530, 190, 201, 51))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(self.pic)
        self.label_7.setGeometry(QtCore.QRect(440, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pb_picture = QtWidgets.QPushButton(self.pic)
        self.pb_picture.setGeometry(QtCore.QRect(740, 190, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_picture.setFont(font)
        self.pb_picture.setStyleSheet("QPushButton {\n"
"background-color: rgb(255, 0, 0);\n"
"     color: black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        self.pb_picture.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/hinh/image/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_picture.setIcon(icon11)
        self.pb_picture.setObjectName("pb_picture")
        self.cb_sort = QtWidgets.QComboBox(self.pic)
        self.cb_sort.setGeometry(QtCore.QRect(950, 280, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.cb_sort.setFont(font)
        self.cb_sort.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px")
        self.cb_sort.setObjectName("cb_sort")
        self.cb_sort.addItem("")
        self.cb_sort.addItem("")
        self.cb_sort.addItem("")
        self.cb_sort.addItem("")
        self.label_8 = QtWidgets.QLabel(self.pic)
        self.label_8.setGeometry(QtCore.QRect(850, 290, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(380, 400, 771, 381))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;\n"
"     \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 400, 341, 381))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;\n"
"     \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 301, 331))
        self.label_4.setStyleSheet("   border-radius: 50px;\n"
"background-color: rgb(255, 255, 255);")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/hinh/image/image (1).png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.groupBox_2.raise_()
        self.pic.raise_()
        self.groupBox.raise_()
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setGeometry(QtCore.QRect(750, 470, 751, 341))
        self.table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px soild #ffff7f\n"
"\n"
"\n"
"\n"
"")
        self.table.setObjectName("table")
        self.table.setColumnCount(6)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cb_compa.setCurrentIndex(0)
        self.cb_process.setCurrentIndex(0)
        self.cb_sort.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPU MANAGER TTA"))
        self.btn_manager.setText(_translate("MainWindow", "Manager"))
        self.btn_type.setText(_translate("MainWindow", "Type"))
        self.btn_logout.setText(_translate("MainWindow", "Log out"))
        self.pb_home.setText(_translate("MainWindow", "Home"))
        self.btn_logout_2.setText(_translate("MainWindow", "Exit"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Menu"))
        self.pic.setTitle(_translate("MainWindow", "CPU Details"))
        self.pb_add.setText(_translate("MainWindow", "Add"))
        self.pb_delete.setText(_translate("MainWindow", "Delete"))
        self.pb_modi.setText(_translate("MainWindow", "Modify"))
        self.pb_cancel.setText(_translate("MainWindow", "Cancel"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Status"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.rd_full.setText(_translate("MainWindow", "Full Box"))
        self.rd_no.setText(_translate("MainWindow", "No Box"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.le_id.setPlaceholderText(_translate("MainWindow", "Type ID"))
        self.le_name.setPlaceholderText(_translate("MainWindow", "Type Name"))
        self.le_price.setPlaceholderText(_translate("MainWindow", "Type Price (VND)"))
        self.label_3.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Price:"))
        self.cb_compa.setItemText(0, _translate("MainWindow", "Not selected"))
        self.cb_compa.setItemText(1, _translate("MainWindow", "Amd"))
        self.cb_compa.setItemText(2, _translate("MainWindow", "Intel"))
        self.label_5.setText(_translate("MainWindow", "Company:"))
        self.label_6.setText(_translate("MainWindow", "Processors:"))
        self.cb_process.setItemText(0, _translate("MainWindow", "Not selected"))
        self.pb_findcompa.setText(_translate("MainWindow", "Find"))
        self.label_7.setText(_translate("MainWindow", "Picture :"))
        self.cb_sort.setItemText(0, _translate("MainWindow", "No Sort"))
        self.cb_sort.setItemText(1, _translate("MainWindow", "Sort by ID"))
        self.cb_sort.setItemText(2, _translate("MainWindow", "Sort by Name"))
        self.cb_sort.setItemText(3, _translate("MainWindow", "Sort by Price"))
        self.label_8.setText(_translate("MainWindow", "Sort Table :"))
        self.groupBox.setTitle(_translate("MainWindow", "Table cpu"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Picture"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Processor"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Company"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Status"))
import Cpu_hinh


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
