# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signupui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Signup(object):
    def setupUi(self, Signup):
        Signup.setObjectName("Signup")
        Signup.setEnabled(True)
        Signup.resize(722, 694)
        Signup.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Signup.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        Signup.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hinh/image/cpu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Signup.setWindowIcon(icon)
        Signup.setAutoFillBackground(False)
        self.widget = QtWidgets.QWidget(Signup)
        self.widget.setGeometry(QtCore.QRect(60, 40, 561, 581))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: transparent;")
        self.widget.setObjectName("widget")
        self.lb_bg_left = QtWidgets.QLabel(self.widget)
        self.lb_bg_left.setGeometry(QtCore.QRect(0, 0, 281, 581))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.lb_bg_left.setFont(font)
        self.lb_bg_left.setStyleSheet("background-color: rgba(255, 255, 255);\n"
"\n"
"border-bottom-left-radius: 100px;")
        self.lb_bg_left.setText("")
        self.lb_bg_left.setObjectName("lb_bg_left")
        self.le_nus_2 = QtWidgets.QLineEdit(self.widget)
        self.le_nus_2.setGeometry(QtCore.QRect(50, 180, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(True)
        self.le_nus_2.setFont(font)
        self.le_nus_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgb(0,0, 0, 240);\n"
"padding-bottom:7px")
        self.le_nus_2.setFrame(False)
        self.le_nus_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_nus_2.setDragEnabled(False)
        self.le_nus_2.setReadOnly(False)
        self.le_nus_2.setObjectName("le_nus_2")
        self.le_npw_2 = QtWidgets.QLineEdit(self.widget)
        self.le_npw_2.setGeometry(QtCore.QRect(50, 240, 211, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setUnderline(True)
        self.le_npw_2.setFont(font)
        self.le_npw_2.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:1px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:rgba(46, 82, 101, 200);\n"
"color:rgb(0,0, 0, 240);\n"
"padding-bottom:7px")
        self.le_npw_2.setFrame(False)
        self.le_npw_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.le_npw_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.le_npw_2.setDragEnabled(False)
        self.le_npw_2.setReadOnly(False)
        self.le_npw_2.setObjectName("le_npw_2")
        self.pb_signup = QtWidgets.QPushButton(self.widget)
        self.pb_signup.setGeometry(QtCore.QRect(50, 360, 190, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pb_signup.setFont(font)
        self.pb_signup.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"    color: black;\n"
"    border: 1px solid black;     \n"
"\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  \n"
"        stop:1 #fff176   \n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  \n"
"        stop:1 #f57c00  \n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hinh/image/sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_signup.setIcon(icon1)
        self.pb_signup.setIconSize(QtCore.QSize(20, 20))
        self.pb_signup.setObjectName("pb_signup")
        self.cb_show_2 = QtWidgets.QCheckBox(self.widget)
        self.cb_show_2.setGeometry(QtCore.QRect(120, 310, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_show_2.setFont(font)
        self.cb_show_2.setObjectName("cb_show_2")
        self.lb_logo = QtWidgets.QLabel(self.widget)
        self.lb_logo.setGeometry(QtCore.QRect(40, -10, 201, 191))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lb_logo.setFont(font)
        self.lb_logo.setStyleSheet("")
        self.lb_logo.setText("")
        self.lb_logo.setTextFormat(QtCore.Qt.RichText)
        self.lb_logo.setPixmap(QtGui.QPixmap(":/hinh/image/logo1.png"))
        self.lb_logo.setScaledContents(True)
        self.lb_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_logo.setObjectName("lb_logo")
        self.lk_login = QtWidgets.QLabel(self.widget)
        self.lk_login.setGeometry(QtCore.QRect(60, 460, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.lk_login.setFont(font)
        self.lk_login.setObjectName("lk_login")
        self.lb_bg_right = QtWidgets.QLabel(self.widget)
        self.lb_bg_right.setGeometry(QtCore.QRect(280, 0, 281, 581))
        self.lb_bg_right.setStyleSheet("border-image: url(:/hinh/image/i7_vs_ryzen_7_a7a7db20c7df41a1b366d8c5afa20d12.webp);\n"
"\n"
"\n"
"border-top-right-radius:100px;")
        self.lb_bg_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lb_bg_right.setText("")
        self.lb_bg_right.setScaledContents(True)
        self.lb_bg_right.setObjectName("lb_bg_right")
        self.lb_icon_newpw = QtWidgets.QLabel(self.widget)
        self.lb_icon_newpw.setGeometry(QtCore.QRect(10, 240, 41, 41))
        self.lb_icon_newpw.setText("")
        self.lb_icon_newpw.setPixmap(QtGui.QPixmap(":/hinh/image/lock.png"))
        self.lb_icon_newpw.setScaledContents(True)
        self.lb_icon_newpw.setObjectName("lb_icon_newpw")
        self.lb_icon_newus = QtWidgets.QLabel(self.widget)
        self.lb_icon_newus.setGeometry(QtCore.QRect(20, 185, 31, 31))
        self.lb_icon_newus.setText("")
        self.lb_icon_newus.setPixmap(QtGui.QPixmap(":/hinh/image/user.png"))
        self.lb_icon_newus.setScaledContents(True)
        self.lb_icon_newus.setObjectName("lb_icon_newus")
        self.lb_icon_haveanaccount = QtWidgets.QLabel(self.widget)
        self.lb_icon_haveanaccount.setGeometry(QtCore.QRect(20, 430, 51, 51))
        self.lb_icon_haveanaccount.setText("")
        self.lb_icon_haveanaccount.setPixmap(QtGui.QPixmap(":/hinh/image/person.png"))
        self.lb_icon_haveanaccount.setScaledContents(True)
        self.lb_icon_haveanaccount.setObjectName("lb_icon_haveanaccount")
        self.exit = QtWidgets.QPushButton(Signup)
        self.exit.setGeometry(QtCore.QRect(620, 0, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"    color: black;\n"
"    border: 1px solid black; \n"
"\n"
"    border-radius:20px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,\n"
"        stop:1 #fff176  \n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d, \n"
"        stop:1 #f57c00  \n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        self.exit.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hinh/image/reject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon2)
        self.exit.setIconSize(QtCore.QSize(20, 20))
        self.exit.setObjectName("exit")
        self.label_2 = QtWidgets.QLabel(Signup)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Signup)
        self.label_3.setGeometry(QtCore.QRect(60, 0, 121, 31))
        self.label_3.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-radius:15px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Signup)
        self.label_4.setGeometry(QtCore.QRect(70, 0, 29, 29))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/hinh/image/sign.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.widget.raise_()
        self.exit.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_2.raise_()

        self.retranslateUi(Signup)
        QtCore.QMetaObject.connectSlotsByName(Signup)

    def retranslateUi(self, Signup):
        _translate = QtCore.QCoreApplication.translate
        Signup.setWindowTitle(_translate("Signup", "Form"))
        self.le_nus_2.setPlaceholderText(_translate("Signup", "New User Name"))
        self.le_npw_2.setPlaceholderText(_translate("Signup", "New Password"))
        self.pb_signup.setText(_translate("Signup", "Sign Up"))
        self.cb_show_2.setText(_translate("Signup", "Show password"))
        self.lk_login.setText(_translate("Signup", "<html><head/><body><p>Have an account ? <a href=\"#\"><span style=\" text-decoration: underline; color:#0000ff;\">LOG IN</span></a></p></body></html>"))
        self.label_2.setText(_translate("Signup", "Sign Up"))
import Cpu_hinh


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Signup = QtWidgets.QWidget()
    ui = Ui_Signup()
    ui.setupUi(Signup)
    Signup.show()
    sys.exit(app.exec_())
