# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Type.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Type(object):
    def setupUi(self, Type):
        Type.setObjectName("Type")
        Type.resize(936, 685)
        icon = QtGui.QIcon()
        Type.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        Type.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        icon.addPixmap(QtGui.QPixmap(":/hinh/image/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Type.setWindowIcon(icon)
        self.logoLabel_2 = QtWidgets.QLabel(Type)
        self.logoLabel_2.setGeometry(QtCore.QRect(50, 50, 231, 261))
        self.logoLabel_2.setStyleSheet("border-bottom-left-radius: 999px;")
        self.logoLabel_2.setText("")
        self.logoLabel_2.setPixmap(QtGui.QPixmap(":/hinh/image/logo1.png"))
        self.logoLabel_2.setScaledContents(True)
        self.logoLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel_2.setObjectName("logoLabel_2")
        self.pb_back_to_Manager = QtWidgets.QPushButton(Type)
        self.pb_back_to_Manager.setGeometry(QtCore.QRect(90, 360, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_back_to_Manager.setFont(font)
        self.pb_back_to_Manager.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hinh/image/exit (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_back_to_Manager.setIcon(icon1)
        self.pb_back_to_Manager.setObjectName("pb_back_to_Manager")
        self.groupBox_6 = QtWidgets.QGroupBox(Type)
        self.groupBox_6.setGeometry(QtCore.QRect(290, 80, 571, 241))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;\n"
"         /* Khoảng cách giữa tiêu đề và nội dung */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_6.setObjectName("groupBox_6")
        self.le_processorname = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_processorname.setGeometry(QtCore.QRect(150, 80, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_processorname.setFont(font)
        self.le_processorname.setObjectName("le_processorname")
        self.le_processor_id = QtWidgets.QLineEdit(self.groupBox_6)
        self.le_processor_id.setEnabled(False)
        self.le_processor_id.setGeometry(QtCore.QRect(150, 30, 381, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_processor_id.setFont(font)
        self.le_processor_id.setClearButtonEnabled(False)
        self.le_processor_id.setObjectName("le_processor_id")
        self.pb_addprocess = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_addprocess.setGeometry(QtCore.QRect(20, 170, 111, 34))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_addprocess.setFont(font)
        self.pb_addprocess.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hinh/image/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_addprocess.setIcon(icon2)
        self.pb_addprocess.setObjectName("pb_addprocess")
        self.pb_cancel_processor = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_cancel_processor.setGeometry(QtCore.QRect(430, 170, 113, 34))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_cancel_processor.setFont(font)
        self.pb_cancel_processor.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hinh/image/paper.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_cancel_processor.setIcon(icon3)
        self.pb_cancel_processor.setObjectName("pb_cancel_processor")
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(30, 40, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_6.setObjectName("label_6")
        self.pb_deleteprocess = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_deleteprocess.setGeometry(QtCore.QRect(160, 170, 108, 34))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_deleteprocess.setFont(font)
        self.pb_deleteprocess.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/hinh/image/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_deleteprocess.setIcon(icon4)
        self.pb_deleteprocess.setObjectName("pb_deleteprocess")
        self.pb_change_processor = QtWidgets.QPushButton(self.groupBox_6)
        self.pb_change_processor.setGeometry(QtCore.QRect(290, 170, 117, 34))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_change_processor.setFont(font)
        self.pb_change_processor.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hinh/image/editing.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_change_processor.setIcon(icon5)
        self.pb_change_processor.setObjectName("pb_change_processor")
        self.label_7 = QtWidgets.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(0, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.label_8.setObjectName("label_8")
        self.le_processorname.raise_()
        self.le_processor_id.raise_()
        self.pb_addprocess.raise_()
        self.pb_cancel_processor.raise_()
        self.pb_deleteprocess.raise_()
        self.pb_change_processor.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_5 = QtWidgets.QLabel(Type)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 891, 581))
        self.label_5.setStyleSheet("border-radius:30px;\n"
"background-color: #1E1E2F;\n"
"background-color: qradialgradient(spread:pad, cx:0.508, cy:0.505818, radius:0.295, fx:0.505, fy:0.517045, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(7, 6, 10, 255));")
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.groupBox_7 = QtWidgets.QGroupBox(Type)
        self.groupBox_7.setGeometry(QtCore.QRect(290, 340, 571, 261))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 2px solid #0078D7; /* Độ dày và màu viền */\n"
"    border-radius: 5px;        /* Bo góc nhẹ nếu muốn */\n"
"    margin-top: 2px;\n"
"         /* Khoảng cách giữa tiêu đề và nội dung */\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.groupBox_7.setObjectName("groupBox_7")
        self.table_processor = QtWidgets.QTableWidget(self.groupBox_7)
        self.table_processor.setGeometry(QtCore.QRect(20, 30, 521, 211))
        self.table_processor.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_processor.setFont(font)
        self.table_processor.setObjectName("table_processor")
        self.table_processor.setColumnCount(2)
        self.table_processor.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_processor.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_processor.setHorizontalHeaderItem(1, item)
        self.pb_exit_pro = QtWidgets.QPushButton(Type)
        self.pb_exit_pro.setGeometry(QtCore.QRect(90, 440, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pb_exit_pro.setFont(font)
        self.pb_exit_pro.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 255, 255);\n"
"     color:black;\n"
"    border: 1px solid black;     /* viền đen */\n"
"    border-radius: 6px;\n"
"    padding: 6px 12px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffffcc,  /* vàng trắng nhạt */\n"
"        stop:1 #fff176   /* vàng nhạt */\n"
"    );\n"
"    color: black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: qlineargradient(\n"
"        x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 #ffb74d,  /* cam nhạt */\n"
"        stop:1 #f57c00   /* cam đậm */\n"
"    );\n"
"    color: black;\n"
"}\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/hinh/image/reject.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_exit_pro.setIcon(icon6)
        self.pb_exit_pro.setObjectName("pb_exit_pro")
        self.label = QtWidgets.QLabel(Type)
        self.label.setGeometry(QtCore.QRect(20, 0, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/hinh/image/link.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Type)
        self.label_2.setGeometry(QtCore.QRect(50, 0, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Type)
        self.label_3.setGeometry(QtCore.QRect(20, 0, 71, 31))
        self.label_3.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-radius:10px;\n"
"    border: 1px solid black; ")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.label_5.raise_()
        self.logoLabel_2.raise_()
        self.groupBox_7.raise_()
        self.pb_back_to_Manager.raise_()
        self.groupBox_6.raise_()
        self.pb_exit_pro.raise_()
        self.label.raise_()
        self.label_2.raise_()

        self.retranslateUi(Type)
        QtCore.QMetaObject.connectSlotsByName(Type)

    def retranslateUi(self, Type):
        _translate = QtCore.QCoreApplication.translate
        Type.setWindowTitle(_translate("Type", "Type"))
        self.pb_back_to_Manager.setText(_translate("Type", "Back"))
        self.groupBox_6.setTitle(_translate("Type", "ADD Processor"))
        self.le_processorname.setPlaceholderText(_translate("Type", "Enter Processor Name"))
        self.le_processor_id.setPlaceholderText(_translate("Type", "Auto"))
        self.pb_addprocess.setText(_translate("Type", "Add"))
        self.pb_cancel_processor.setText(_translate("Type", "Cancel"))
        self.label_6.setText(_translate("Type", "Processor ID:"))
        self.pb_deleteprocess.setText(_translate("Type", "Delete"))
        self.pb_change_processor.setText(_translate("Type", "Change"))
        self.label_8.setText(_translate("Type", "Processor Name:"))
        self.groupBox_7.setTitle(_translate("Type", "ADD Processor"))
        item = self.table_processor.horizontalHeaderItem(0)
        item.setText(_translate("Type", "Processor ID"))
        item = self.table_processor.horizontalHeaderItem(1)
        item.setText(_translate("Type", "Processor Name"))
        self.pb_exit_pro.setText(_translate("Type", "Exit"))
        self.label_2.setText(_translate("Type", "Type"))
import Cpu_hinh


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Type = QtWidgets.QWidget()
    ui = Ui_Type()
    ui.setupUi(Type)
    Type.show()
    sys.exit(app.exec_())
